### ISSUE TITLE
grain_hill_driver.py hangs under many model BCs

### ISSUE THREAD

**Issue by SiccarPoint** [gregtucker/grain_hills#2] opened 2018-05-14 14:59 UTC
As I noted a couple of weeks ago, there's a significant bug in here that I can't diagnose on my own that causes this model to terminally hang under many different model conditions. To reproduce in your grain_hill_driver code, simply set the base of the grid much longer than the height - I used a 15 x 101 grid. The model will lock up completely as soon as the rising hill of material impinges on the top grid edge (though this will also happen if material is advected laterally into a side edge).

This matters as it stymies my attempts to turn this into a facet model with lateral advection. Once the facet touches the side or top, game over.

**Comment by gregtucker** [comment] 2018-06-04 21:59
I can reproduce this with the **grain_hill_driver.py** script (now added to repo) and the following input file:

# GrainHill input file for reproducing/testing "top hit bug"
number_of_node_rows: 15
number_of_node_columns: 50
cell_size: 0.1
grav_accel: 9.8
friction_coef: 1.0
run_duration: 17.0
output_name: 'test'
uplift_interval: 1.0
uplift_duration: 20000.0
disturbance_rate: 0.001
weathering_rate: 0.001
rock_state_for_uplift: 8
opt_rock_collapse: 1
opt_track_grains: False
show_plots: True
plot_to_file: True
plot_interval: 1.0
output_interval: 1.0e20
report_interval: 60.0

**Comment by gregtucker** [comment] 2018-06-07 20:50
This issue seems to be solved by a change to hex_lattice_tectonicizer (in Landlab) that no longer moves uplifted nodes into the top row of the grid. Closing this issue for now; @SiccarPoint please re-post if it recurs when using the latest Landlab master.

**Closed as completed by gregtucker** 2018-06-07 20:50 UTC

**Comment by SiccarPoint** [comment] 2018-06-08 15:49
Afraid not - this fixed the standard uplifter, but the top hit bug persists with the fault_uplifter. However, my PR #3 does appear to now sort this out fully. The key is to set the top and left boundaries to COSED, not FIXED_VALUE, such that CelllabCTS stops listing them in its transitions entirely.

With this in mind, you might (?) want to consider reverting your change to the lattice_tectonizer in LL proper. At the moment, it means that the top edge is handled separately differently from the left and right edges under some circumstances, I believe. PR #3 should remove the problem without it.
